config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, path: 'admin'
  devise_for :employees, path: 'employees'

  resources :employees, only: %i[show edit update]
  resources :kudos
  resources :orders, only: %i[index new create]
  resources :rewards, only: %i[index show]

  root 'kudos#index'

  namespace :admin do
    root to: 'pages#dashboard'
    resources :categories
    resources :category_rewards
    resources :company_values
    resources :employees, except: %i[new create] do
      collection do
        get 'edit_kudos_for_all'
        patch 'update_kudos_for_all'
      end
    end
    resources :kudos
    resources :orders, only: %i[index update]
    resources :reward_codes, only: %i[create edit update destroy]
    resources :rewards do
      collection { post :import }
    end
  end
end

app/models/reward.rb
# frozen_string_literal: true

class Reward < ApplicationRecord
  enum delivery_method: { online: 0, post: 1 }

  validates :title, :description, :price, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 1 }
  validates :photo, content_type: ['image/png', 'image/jpeg']

  has_many :orders, dependent: :destroy
  has_many :employees, through: :orders
  has_many :reward_codes, dependent: :destroy

  has_many :category_rewards, dependent: :destroy
  has_many :categories, through: :category_rewards

  has_one_attached :photo

  def self.import(file)
    ActiveRecord::Base.transaction do
      CSV.foreach(file.path, headers: true) do |row|
        reward_hash = row.to_h
        number_of_codes = reward_hash.length - 5
        reward = Reward.find_by!(slug: reward_hash['slug'])
        Reward.update(reward.id, title: reward_hash['title'],
                                 description: reward_hash['description'],
                                 price: reward_hash['price'],
                                 delivery_method: reward_hash['delivery_method'])
        if number_of_codes > 9
          (1..number_of_codes).each do |i|
            reward.reward_codes.build(code: reward_hash["code#{i}"]) if RewardCode.find_by(code: reward_hash["code#{i}"]).nil?
          end
        end
        reward.save!
      end
    end
  end
end

app/controllers/admin/rewards_controller.rb
# frozen_string_literal: true

module Admin
  class RewardsController < AdminController
    def index
      render :index, locals: { rewards: Reward.all }
    end

    def import
      if params[:file].nil?
        redirect_to admin_rewards_path, notice: 'No file selected.'
      elsif Reward.import(params[:file])
        redirect_to admin_rewards_path, notice: 'Rewards was successfully imported.'
      end
    rescue ActiveRecord::RecordInvalid, CSV::MalformedCSVError => e
      redirect_to admin_rewards_path, notice: "Check your csv file - #{e}"
    end

    def show
      render :show, locals: { reward: reward }
    end

    def new
      render :new, locals: { reward: Reward.new }
    end

    def edit
      render :edit, locals: { reward: reward }
    end

    def create
      reward = Reward.new(reward_params)
      reward.slug = reward.title.parameterize
      if reward.save
        redirect_to admin_rewards_path(reward), notice: 'Reward was successfully created.'
      else
        render :new, locals: { reward: reward }
      end
    end

    def update
      reward.slug = reward_params[:title].parameterize
      if reward.update(reward_params)
        redirect_to admin_rewards_path(reward), notice: 'Reward was successfully updated.'
      else
        render :edit, locals: { reward: reward }
      end
    end

    def destroy
      reward.destroy
      redirect_to admin_rewards_url, notice: 'Reward was successfully destroyed.'
    end

    private

    def reward
      @reward ||= Reward.find(params[:id])
    end

    def reward_params
      params.require(:reward).permit(:title, :description, :price, :photo, :delivery_method, category_ids: [])
    end
  end
end

app/controllers/rewards_controller.rb
# frozen_string_literal: true

class RewardsController < ApplicationController
  REWARDS_PER_PAGE = 10

  def index
    @page = params.fetch(:page, 0).to_i
    if params[:category_id].to_i.positive?
      @number_of_pages = (RewardSearch.new(params).results.count / REWARDS_PER_PAGE).ceil
      if params[:page].to_i <= @number_of_pages
        render :index, locals: { rewards: RewardSearch.new(params).results.offset(@page * REWARDS_PER_PAGE).limit(REWARDS_PER_PAGE) }
      else
        redirect_to rewards_path, notice: "Enter page in range 1 to #{@number_of_pages + 1}."
      end
    else
      @number_of_pages = (RewardSearch.new.results.count / REWARDS_PER_PAGE).ceil
      if params[:page].to_i <= @number_of_pages
        render :index, locals: { rewards: RewardSearch.new.results.offset(@page * REWARDS_PER_PAGE).limit(REWARDS_PER_PAGE) }
      else
        redirect_to rewards_path, notice: "Enter page in range 1 to #{@number_of_pages + 1}."
      end
    end
  end

  def show
    render :show, locals: { reward: reward }
  end

  private

  def reward
    @reward ||= Reward.find(params[:id])
  end

  def reward_params
    params.require(:reward).permit(:title, :description, :price, :photo)
  end
end

app/views/admin/rewards/_form.html.erb
<%= form_with(model: [ :admin, reward ]) do |form| %>
  <% if reward.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reward.errors.count, "error") %> prohibited this reward from being saved:</h2>

      <ul>
        <% reward.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title %><br>
    <%= form.text_field :title, class:"form-control" %>
  </div>
  <div class="field form-group">
    <%= form.label :description %><br>
    <%= form.text_field :description, class:"form-control" %>
  </div>
  <div class="field form-group">
    <%= form.label :price %><br>
    <%= form.text_field :price, class:"form-control" %>
  </div>
  <div class="field">
    <%= form.label :category_id %>
    </br>
    <%= form.collection_check_boxes :category_ids, Category.all, :id, :title do |check_box| %>
      <div class="form-check">
        <%= check_box.label class: 'form-check-label' do %>
          <%= check_box.check_box class: 'form-check-input' %>
          <%= check_box.object.title %>
      </div>
        <% end %>
    <% end %>
  </div>
  <div class="field form-group">
    <%= form.label :photo %><br>
    <%= form.file_field :photo, class:"form-control" %>
  </div>
  <div class="field form-group">
    <%= form.label :delivery_method %><br>
    <%= form.select :delivery_method, Reward.delivery_methods.keys, {}, class:'form-control' %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/rewards/_index_codes.html.erb
<table class="table table-responsive table-hover">
  <thead>
    <tr class="text-center">
    <th>Code</th>
    <th>Status</th>
    <th>Action</th>
  </tr>
  </thead>
  <tbody>
    <% reward.reward_codes.each do |code| %>
      <tr>
      <td style="text-align: center"><%= code.code %></td>
      <td style="text-align: center"><%= code.status %></td>
      <td style="text-align: center">
      <%= link_to ' Edit', edit_admin_reward_code_path(code.id), class:"btn btn-outline-secondary btn-sm bi bi-pencil" %>
      </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/rewards/edit.html.erb
<h1>Editing Reward</h1>

<%= render 'form', reward: reward %>
<br>
<%= link_to 'Back', admin_rewards_path, class:"btn btn-dark" %> |
<%= link_to 'Delete', admin_reward_path(reward), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>

app/views/admin/rewards/index.html.erb
<h1>Rewards</h1>
<div class="w-25">
<%= form_tag import_admin_rewards_path, multipart: true, class: "form-inline" do %>
<div class="field form-group">
  <%= file_field_tag :file, class:"form-control" %>
</div>
<div class="form-group">
  <%= submit_tag "import CSV"%>
</div>
<% end %>
</div>
<br>
<table class="table table-striped table-bordered w-auto shadow-sm">
  <thead  class="table-success">
    <tr class="text-center">
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Photo</th>
      <th>Delivery method</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% rewards.each do |reward| %>
      <tr>
        <td style="vertical-align:middle"><%= reward.title %></td>
        <td style="vertical-align:middle"><%= reward.description %></td>
        <td style="text-align: center; vertical-align:middle"><%= reward.price %></td>
        <td style="text-align: center">
          <% if reward.photo.persisted?%>
            <%= image_tag reward.photo, width: '50px' %>
          <%end%>
        </td>
        <td style="text-align: center; vertical-align:middle"><%= reward.delivery_method %></td>
        <td class="btn-group">
        <%= link_to ' Edit', edit_admin_reward_path(reward), class:"btn btn-outline-secondary btn-sm bi bi-pencil" %>
        <%= link_to ' Show', admin_reward_path(reward), class:"btn btn-outline-secondary btn-sm bi bi-pencil" %>
        <%= link_to ' Delete', admin_reward_path(reward), 
        method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm bi bi-trash2" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to '<i class="bi bi-file-earmark-plus"> </i>New Reward'.html_safe, new_admin_reward_path, class:"btn btn-secondary" %>

app/views/admin/rewards/new.html.erb
<h1>New Reward</h1>

<%= render 'form', reward: reward %>
<br>
<%= link_to 'Back', admin_rewards_path, class:"btn btn-secondary btn-sm"  %>

app/views/admin/rewards/show.html.erb
<h2>Reward</h2>
<div class="card shadow w-50 mx-auto">
  <div class="card-header text-center", style="background-color:#ffcd38;">
    <h5 class="mt-2", style="color:#ffffff;"><%= reward.title %></h5>
  </div>
  <div class="card-body">
    <h5 class="card-title">Description</h5>
    <p class="card-text"><%= reward.description %><p>

    Price: <%= reward.price %><br>

    Categories:
    <ul>
        <% reward.categories.each do |category| %>
            <li><%= category.title %></li>
        <% end %>
    </ul>

    <div class="text-center">
      <% if reward.photo.persisted?%>
        <%= image_tag reward.photo, width: '240px' %>
      <%end%>
    </div>

    <%= render 'index_codes', reward: reward %>

    <%= link_to 'Edit', edit_admin_reward_path(reward), class:"btn btn-secondary btn-sm" %> |
    <%= link_to 'Back', admin_rewards_path, class:"btn btn-secondary btn-sm" %>
  </div>
</div>