config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, path: 'admin'
  devise_for :employees, path: 'employees'

  resources :employees, only: %i[show edit update]
  resources :kudos
  resources :orders, only: %i[index new create]
  resources :rewards, only: %i[index show]

  root 'kudos#index'

  namespace :admin do
    root to: 'pages#dashboard'
    resources :categories
    resources :category_rewards
    resources :company_values
    resources :employees, except: %i[new create] do
      collection do
        get 'edit_kudos_for_all'
        patch 'update_kudos_for_all'
      end
    end
    resources :kudos
    resources :orders, only: %i[index update]
    resources :reward_codes, only: %i[create edit update destroy]
    resources :rewards do
      collection { post :import }
    end
  end
end

app/views/admin/_adminheader.html.erb
<nav class="navbar sticky-top navbar-expand-md navbar-dark shadow" style="background-color: #242582;">
  <div class="container">
    <i>
      <%= link_to "ERP Admin", root_path, class:"navbar-brand mb-0 h1" %>
    </i>
    
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Employees", admin_employees_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Kudos", admin_kudos_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Add Kudos", edit_kudos_for_all_admin_employees_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Company values", admin_company_values_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Rewards", admin_rewards_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Orders (#{Order.not_delivered.count})", admin_orders_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Categories", admin_categories_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
    <div class="collapse navbar-collapse d-flex flex-row-reverse bd-highlight">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to ' Log Out', destroy_admin_user_session_path, method: :delete, class: "btn btn-outline-light btn-sm bi bi-box-arrow-right" %>
        </li>
      </ul>
    </div>
  </div>
</nav>