config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, path: 'admin'
  devise_for :employees, path: 'employees'

  resources :employees, only: %i[show edit update]
  resources :kudos
  resources :orders, only: %i[index new create]
  resources :rewards, only: %i[index show]

  root 'kudos#index'

  namespace :admin do
    root to: 'pages#dashboard'
    resources :categories
    resources :category_rewards
    resources :company_values
    resources :employees, except: %i[new create] do
      collection do
        get 'edit_kudos_for_all'
        patch 'update_kudos_for_all'
      end
    end
    resources :kudos
    resources :orders, only: %i[index update]
    resources :reward_codes, only: %i[create edit update destroy]
    resources :rewards do
      collection { post :import }
    end
  end
end

app/models/employee.rb
# frozen_string_literal: true

class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, presence: true

  has_many :given_kudos, class_name: 'Kudo', foreign_key: 'giver_id', dependent: :destroy, inverse_of: :giver
  has_many :received_kudos, class_name: 'Kudo', foreign_key: 'receiver_id', dependent: :destroy, inverse_of: :receiver
  has_many :orders, dependent: :destroy
  has_many :rewards, through: :orders

  def kudo_points
    received_kudos.count - orders.sum(&:snapshot_price).to_i
  end

  def full_name
    if first_name && last_name
      "#{first_name} #{last_name}"
    else
      email
    end
  end

  def display_name
    first_name || email
  end
end

app/controllers/admin/employees_controller.rb
# frozen_string_literal: true

module Admin
  class EmployeesController < AdminController
    def index
      render :index, locals: { employees: Employee.includes(:orders).all }
    end

    def edit
      render :edit, locals: { employee: employee }
    end

    def update
      params[:employee].compact_blank! if params[:employee][:password].blank?
      if employee.update(employee_params)
        redirect_to admin_employees_path, notice: 'Employee was successfully updated.'
      else
        render :edit, locals: { employee: employee }
      end
    end

    def destroy
      employee.destroy
      redirect_to admin_employees_path, notice: 'Employee was successfully destroyed.'
    end

    def edit_kudos_for_all
      render :update_kudos_for_all, locals: { employees: Employee.all }
    end

    def update_kudos_for_all
      if add_kudos_param >= 1 && add_kudos_param <= 20

        begin
          ActiveRecord::Base.transaction do
            Employee.find_each do |employee|
              employee.number_of_available_kudos += add_kudos_param
              employee.save!
            end
          end
        rescue ActiveRecord::RecordNotSaved => e
          render :new, notice: "Something go wrong. Please try again. #{e.message}"
        end

        redirect_to admin_employees_path, notice: 'Number of available Kudos was successfully added to Employees.'
      else
        redirect_to edit_kudos_for_all_admin_employees_path, notice: 'Enter a number between 1 and 20.'
      end
    end

    private

    def employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :email, :password, :number_of_available_kudos)
    end

    def add_kudos_param
      params[:add_kudos].to_i
    end
  end
end

app/controllers/employees_controller.rb
# frozen_string_literal: true

class EmployeesController < ApplicationController
  before_action :authenticate_employee!

  def show
    render :show, locals: { employee: current_employee }
  end

  def edit
    render :edit, locals: { employee: current_employee }
  end

  def update
    authorize current_employee
    if params[:employee][:first_name].blank? || params[:employee][:last_name].blank?
      redirect_to edit_employee_path, notice: 'First name and last name cannot be empty.'
    elsif current_employee.update(employee_params)
      redirect_to root_path, notice: 'Your name was successfully added.'
    else
      render :edit, locals: { employee: current_employee }
    end
  end

  private

  def employee_params
    params.require(:employee).permit(policy(current_employee).permitted_attributes)
  end
end

app/views/admin/employees/_form.html.erb
<%= form_with(model: [ :admin, employee ]) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name, class:"form-control" %>
  </div>
<br>
  <div class="field form-group">
    <%= form.label :last_name %><br>
    <%= form.text_field :last_name, class:"form-control" %>
  </div>
<br>
  <div class="field form-group">
    <%= form.label :number_of_available_kudos %>
    <%= form.number_field :number_of_available_kudos, min: 0, class:"form-control"%>
  </div>
<br>
  <div class="field form-group">
    <%= form.label :email %><br>
    <%= form.text_field :email, autofocus: true, class:"form-control" %>
  </div>
<br>
  <div class="field form-group">
    <%= form.label :password %><br>
    <%= form.text_field :password, placeholder:"Enter new password, leave blank if you don't want to change it.", class:"form-control" %>
  </div>
<br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/employees/add_kudos_for_all.erb
<div class="card shadow mx-auto" style="width: 25rem;">
  <div class="card-header text-center">
    <div class="field">
      <%= form_with url: add_kudos_for_all_admin_employees_path, method: :patch do |form| %>
        <%= form.label :add_kudos, "Add number of available Kudos to Employees:" %>
        <%= form.number_field :add_kudos, in: 1..20, value: 10 %>
        <%= form.submit "Add" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/employees/edit.html.erb
<h1>Editing Employee: <%=employee.first_name%> <%=employee.last_name%></h1>
<%= render 'form', employee: employee %>
<br>
<%= link_to 'Back', admin_employees_path, class:"btn btn-dark" %> |
<%= link_to 'Delete', admin_employee_path(employee), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>

app/views/admin/employees/index.html.erb
<h1>Employees</h1>
<div class="d-flex justify-content-center">
  <table class="table table-borderless table-responsive table-hover shadow card-1 w-auto">
    <thead>
      <tr class="text-center", id="table__header">
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Available kudos</th>
      <th>Kudo point</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% employees.each do |employee| %>
      <tr class="border-bottom">
        <td><%= employee.first_name unless employee.first_name.nil? %></td>
        <td><%= employee.last_name unless employee.last_name.nil? %></td>
        <td><%= employee.email %></td>
        <td class="text-center"><%= employee.number_of_available_kudos %></td>
        <td class="text-center"><%= employee.kudo_points %></td>
        <td class="btn-group">
        <%= link_to ' Edit', edit_admin_employee_path(employee), class:"btn btn-outline-secondary btn-sm bi bi-pencil" %>
        <%= link_to ' Delete', admin_employee_path(employee), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm bi bi-trash2" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/employees/update_kudos_for_all.erb
<div class="card shadow mx-auto" style="width: 25rem;">
  <div class="card-header text-center">
    <div class="field">
      <%= form_with url: update_kudos_for_all_admin_employees_path, method: :patch do |form| %>
        <%= form.label :add_kudos, "Add number of available Kudos to Employees:" %>
        <%= form.number_field :add_kudos, in: 1..20, value: 10 %>
        <%= form.submit "Add" %>
      <% end %>
    </div>
  </div>
</div>