config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, path: 'admin'
  devise_for :employees, path: 'employees'

  resources :employees, only: %i[show edit update]
  resources :kudos
  resources :orders, only: %i[index new create]
  resources :rewards, only: %i[index show]

  root 'kudos#index'

  namespace :admin do
    root to: 'pages#dashboard'
    resources :categories
    resources :category_rewards
    resources :company_values
    resources :employees, except: %i[new create] do
      collection do
        get 'edit_kudos_for_all'
        patch 'update_kudos_for_all'
      end
    end
    resources :kudos
    resources :orders, only: %i[index update]
    resources :reward_codes, only: %i[create edit update destroy]
    resources :rewards do
      collection { post :import }
    end
  end
end

app/models/kudo.rb
# frozen_string_literal: true

class Kudo < ApplicationRecord
  belongs_to :giver, class_name: 'Employee'
  belongs_to :receiver, class_name: 'Employee'
  belongs_to :company_value

  validates :title, :content, presence: true
end

app/controllers/admin/kudos_controller.rb
# frozen_string_literal: true

module Admin
  class KudosController < AdminController
    def index
      render :index, locals: { kudos: Kudo.includes(:company_value, :giver, :receiver).all }
    end

    def show
      render :show, locals: { kudo: kudo }
    end

    def new
      render :new, locals: { kudo: Kudo.new }
    end

    def edit
      render :edit, locals: { kudo: kudo }
    end

    def create
      kudo = Kudo.new(kudo_params)
      if kudo.save
        redirect_to admin_kudo_path(kudo), notice: 'Kudo was successfully created.'
      else
        render :new, locals: { kudo: kudo }
      end
    end

    def update
      if kudo.update(kudo_params)
        redirect_to admin_kudo_path(kudo), notice: 'Kudo was successfully updated.'
      else
        render :edit, locals: { kudo: kudo }
      end
    end

    def destroy
      kudo.destroy
      redirect_to admin_kudos_url, notice: 'Kudo was successfully destroyed.'
    end

    private

    def kudo
      @kudo = Kudo.find(params[:id])
    end

    def kudo_params
      params.require(:kudo).permit(:title, :content, :giver_id, :receiver_id, :company_value_id)
    end
  end
end

app/controllers/kudos_controller.rb
# frozen_string_literal: true

class KudosController < ApplicationController
  before_action :authenticate_employee!
  before_action :check_kudo_giver, only: %i[edit update destroy]

  def index
    render :index, locals: { kudos: Kudo.includes(:company_value, :giver, :receiver).all }
  end

  def show
    render :show, locals: { kudo: kudo }
  end

  def new
    if current_employee.number_of_available_kudos < 1
      redirect_to kudos_path, notice: 'You have no kudos available to give.'
    else
      render :new, locals: { kudo: Kudo.new }
    end
  end

  def edit
    authorize kudo
    render :edit, locals: { kudo: kudo }
  end

  def create
    unless current_employee.number_of_available_kudos >= 1
      redirect_to kudos_path,
                  notice: 'You have no kudos available to give.' && return
    end
    kudo = Kudo.new(kudo_params)
    kudo.giver = current_employee
    if kudo.save
      current_employee.number_of_available_kudos -= 1
      current_employee.save
      redirect_to kudos_path,
                  notice: 'Kudos was successfully created. If you want to change something, you have 5 minutes to edit your kudo.'
    else
      render :new, locals: { kudo: kudo }
    end
  end

  def update
    authorize kudo
    if kudo.update(kudo_params)
      redirect_to kudos_path, notice: 'Kudos was successfully updated.'
    else
      render :edit, locals: { kudo: kudo }
    end
  end

  def destroy
    authorize kudo
    kudo.destroy
    redirect_to kudos_url, notice: 'Kudos was successfully destroyed.'
  end

  def check_kudo_giver
    redirect_to kudos_path, notice: 'You are not authorized to edit this kudo.' unless kudo.giver == current_employee
  end

  private

  def kudo_params
    params.require(:kudo).permit(:title, :content, :receiver_id, :company_value_id)
  end

  def kudo
    @kudo = Kudo.find(params[:id])
  end
end

app/views/kudos/_form.html.erb
<%= form_with model: kudo do |form| %>
 <% if kudo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kudo.errors.count, "error") %> prohibited this kudo from being saved:</h2>

      <ul>
        <% kudo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title %><br>
    <%= form.text_field :title, class:"form-control" %>
  </div>
<br>
  <div class="field form-group">
    <%= form.label :content %><br>
    <%= form.text_area :content, class:"form-control" %>
  </div>
<br>
  <div class="field form-group">
    <%= form.label :receiver_id %><br>
    <%= form.collection_select :receiver_id, Employee.all, :id, :full_name, class:"form-control" %>
  </div>
<br>
  <div class="field form-group">
    <%= form.label :company_value_id %><br>
    <%= form.collection_select :company_value_id, CompanyValue.all, :id, :title, class:"form-control" %>
  </div>
<br>
  <div class="action">
    <%= form.submit %>
  </div>
<% end %>

app/views/kudos/edit.html.erb
<h1>Edit Kudo</h1>
<br>
<%= render 'form', kudo: kudo %>
<br>
<%= link_to 'Back', kudos_path, class:"btn btn-dark" %>
<%= link_to 'Delete', kudo, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>

app/views/kudos/index.html.erb
<h1>All Kudos</h1>
<div class="d-flex justify-content-center">
  <table class="table table-borderless table-responsive table-hover shadow card-1 w-auto">
    <thead>
      <tr class="text-center", id="table__header">
        <th>Title</th>
        <th>Content</th>
        <th>Giver</th>
        <th>Receiver</th>
        <th>Company value</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% kudos.each do |kudo| %>
        <tr class="border-bottom">
          <td><%= kudo.title %></td>
          <td><%= kudo.content %></td>
          <td class="text-center"><%= kudo.giver.full_name %></td>
          <td class="text-center"><%= kudo.receiver.full_name %></td>
          <td class="text-center"><%= kudo.company_value.title %></td>
          <% if kudo.giver == current_employee %>
          <td class="btn-group">
          <% if policy(kudo).update? %>
            <%= link_to ' Edit', edit_kudo_path(kudo), class:"btn btn-outline-secondary btn-sm bi bi-pencil" %>
            <%= link_to ' Delete', kudo_path(kudo), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm bi bi-trash2" %>
          <% end %>
          </td>
          <% else %>
          <td></td>
          <% end %>
        </tr>
      <% end %>   
    </tbody>
    <tfoot>
      <td class="text-center" colspan="6">
        <%= link_to ' New Kudo', new_kudo_path, class:"btn btn-warning btn-sm bi bi-file-earmark-plus" %>
      </td> 
    </tfoot>
  </table>
</div>

app/views/kudos/new.html.erb
<h1>New Kudos</h1>

<%= render 'form', kudo: kudo %>
<br/>
<%= link_to 'Back', kudos_path, class: 'btn btn-secondary' %>